-- AlterTable
ALTER TABLE "RentalRequest" ALTER COLUMN "from" SET DATA TYPE DATE,
ALTER COLUMN "to" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "startDate" SET DATA TYPE DATE,
ALTER COLUMN "endDate" SET DATA TYPE DATE;
